### PR TITLE
Upgrade react-scripts to latest version (2.1.3)

### PR DESCRIPTION
**Pull request by toolness**
~~**Note: This is a PR against #95, not `master`! I will re-target it to `master` once #95 is merged.**~~

This is an attempt to upgrade react-scripts to the latest version--partially just to stay up-to-date, but also because 2.1.0 and higher [support Typescript out of the box](https://facebook.github.io/create-react-app/docs/adding-typescript), which could be useful in sharing code between this app and the tenants app, specifically for #53.

## To do

- [x] Upgrade from 1.0.10 to 2.0.3.
- [x] Upgrade from 2.0.3 to the latest 2.x release.
- [x] Fix all new linter warnings.
- [x] Ensure that at least Node 8 is used in production and on @sraby's dev machine, as [2.x drops support for node 6](https://github.com/facebook/create-react-app/blob/1deb811c5d91ac6d337d2fd4e4f36c7d8c352ebd/CHANGELOG.md#node-6-is-no-longer-supported). **Update: see #100 for more details.**
- [x] Add polyfills for IE11 at the very least, since [IE polyfills are no longer included by default in 2.x](https://github.com/facebook/create-react-app/blob/1deb811c5d91ac6d337d2fd4e4f36c7d8c352ebd/CHANGELOG.md#polyfills-for-ie-9-ie-10-and-ie-11-are-no-longer-included-by-default-but-you-can-opt-in). Then verify that the app still works on IE11.
- [x] Verify that the app doesn't use `require.ensure()` (also a breaking change in 2).
- [x] Ensure dynamic `import()` follows new semantics in 2 (not an issue, we don't use dynamic import)
- [x] Ensure testing suite still works (Jest's default environment was changed to `jsdom` in 2 but we don't have any tests in it yet).
- [x] Ensure the proxy configuration still works (another breaking change in 2).
- [x] Ensure we don't use `PropTypes` in weird ways (another breaking change in 2).

### CODE REVIEW

**Comment by sraby** [comment]
@toolness I'm currently using node v8.9.1 on my dev machine :)

**Comment by toolness** [comment]
@sraby Ok I think this is good to go! I kicked the tires on IE11, Edge, Chrome, Firefox, and iPhone Safari.

**Comment by toolness** [comment]
Er, actually hold on a sec @sraby... @romeboards is investigating whether the current WoW supports IE9 and IE10. If it does, then I will have to add the react polyfill thing for it (and we will have to test those browsers going forward, which is hard even for me on Windows b/c I only have IE11 here, so I guess I will have to use BrowserStack).

**Comment by toolness** [comment]
Ok, Dan says we're only supporting IE11 so I think this is indeed good to go.

**Pull request merged**
