### PR TITLE
Add special Wowza styling to homepage and rest of site

### PR DESCRIPTION
**Pull request by sraby**
This PR implements Tahnee's designs for the new WOWZA homepage and notification banner, and also carries through some of the color choices into internal pages as per Tahnee's feedback.

### CODE REVIEW

**Comment by sraby** [comment]
[sc-8984]

**Comment by sraby** [comment]
[sc-8964]

**Comment by sraby** [comment]
[sc-8994]

**Review by austensen — APPROVED** [review]
This all looks great! Love the new design, it looks amazing. It tested it out locally and it's all working. The only minor thing I noticed is that when you switch between old and new versions the example portfolios flicker a bit as the images reload.

**Pull request merged**
