### PR TITLE
Content and styling tweaks to the network chart and big portfolio warning on WOWZA

### PR DESCRIPTION
**Pull request by sraby**
Simple content and styling tweaks.

### CODE REVIEW

**Comment by sraby** [comment]
[sc-9096]

**Comment by sraby** [comment]
[sc-9092]

**Comment by sraby** [comment]
[sc-9093]

**Review by austensen — APPROVED** [review]
This all looks great! I tested it out and it all works as expected. I tried clicking another property to add the new annotation, then clicking back to make sure it went away and didn't double up when search and detail properties are the same. I think this does help clarify how your searched properties fit into the portfolio.

**Pull request merged**
